# Generated by Django 4.0.2 on 2022-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateField()),
                ('image', models.ImageField(blank=True, default='book-images/74165.jpg', null=True, upload_to='book-images/')),
            ],
        ),
    ]
