# Generated by Django 4.0.2 on 2022-06-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_book_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_created',
            field=models.DateField(),
        ),
    ]
