# Generated by Django 4.0.2 on 2022-06-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book-images/74165.jpg', upload_to='book-images/'),
        ),
    ]
