# Generated by Django 3.2.9 on 2022-06-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='book',
            field=models.ManyToManyField(related_name='user', to='main.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
